import type { Metadata } from "next";
import { ApolloWrapper } from "@app/lib/apollo";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Advanced Apollo Starter",
  description: "Generated by create next app",
};

type IRootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: IRootLayoutProps) => (
  <html lang="en">
    <body>
      <ApolloWrapper>{children}</ApolloWrapper>
    </body>
  </html>
);

export default RootLayout;
